# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: ANT-2-MQTT
version: "1.5.1"
slug: ant-2-mqtt
description: Receive ANT+ fitness tracker messages and send them to MQTT for homeassistant integration
url: "https://github.com/millskyle/hass_ant-2mqtt"
usb: true
udev: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
host_network: true
options:
  mqtt_broker: "localhost"
  mqtt_port: 1883
  mqtt_user: "mqtt"
  mqtt_password: "mqtt"
  wheel_circumference_m: 2.100
schema:
  mqtt_broker: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  wheel_circumference_m: float