# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: ANT-2-MQTT
version: "1.4.6"
slug: ant-2-mqtt
description: Receive ANT+ fitness tracker messages and send them to MQTT for homeassistant ingestion
url: "https://github.com/millskyle/hass_ant-2mqtt"
usb: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
#devices: 
#  - /dev/bus/usb:/dev/bus/usb:rwm
